#Publish all joint states ----------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

#Velocity Controller
velocity_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    - joint8
    - joint9
    - joint10
    - joint11
